### ISSUE TITLE
[Feature Request] Press any key to continue

### ISSUE THREAD

**Issue by AZMCode** [keegandonley/input-deno#21]
While Deno offers `alert()`, that pauses execution until the Enter key is pressed, it would be nice to have an async alternative that also pauses until *any* key is pressed.

**Comment by keegandonley** [comment]
@AZMCode Well, I certainly let this project get stale for a while there. Had some personal reasons I needed to take a step back, but I was able to implement this for you tonight, you can find it available in release 2.0.3: https://github.com/keegandonley/input-deno/releases/tag/2.0.3

Please let me know if this does what you're hoping (if you even still need it 😬)

**Comment by keegandonley** [comment]
I've posted a bit about the release on my blog here: https://keegandonley.com/blog/input-deno-v2.0.3-released
