### ISSUE TITLE
input.choose returns false for all options

### ISSUE THREAD

**Issue by ToothpickFactory** [keegandonley/input-deno#3]
I am attempting to use the input.choose method but the result is always an array of false values. Here is what I am running

```
import InputLoop from "https://deno.land/x/input/index.ts";
const input = new InputLoop();
const weapon = await input.choose(["sword", "bow", "dagger"]);
console.log(weapon);
```

I am running this in Powershell 7 on Windows.

**Comment by keegandonley** [comment]
@ToothpickFactory Thanks is for reporting this! I haven’t tested this yet using Powershell but I’ll try to get my hands on a Windows machine and look into this tonight. My guess is the console input doesn’t come back the same way it does on MacOS.

**Comment by ToothpickFactory** [comment]
No problem. Looking to see if I can figure it out. Narrowed it down to the TextDecoder() in the read method. It does return back "correctly" what was sent to it. Heck it even says that it's a string. When I try and compare a "2" to a 2 entered in via the console it reports that they do not equal. It's really bizarre.

**Comment by keegandonley** [comment]
@ToothpickFactory I can reproduce this on a box running windows server on AWS. Investigating now

**Comment by keegandonley** [comment]
@ToothpickFactory Thanks for bearing with me on this one. I forgot to fully strip Windows carriage returns. You should see the correct behavior in the latest release: https://github.com/keegandonley/input-deno/releases/tag/1.0.1

**Comment by ToothpickFactory** [comment]
Thanks for the speedy fix!
