### ISSUE TITLE
Advanced Input History

### ISSUE THREAD

**Issue by keegandonley** [keegandonley/input-deno#4]
Track the questions asked to the user and the answers given in order

TODO:

- [x] Store history
  - [x] Save
- [x] Retrieve history
  - [x] Shift
  - [x] Pop
  - [x] Length
  - [x] Get all
- [ ] Interact with history results
- [ ] Tests
  - [x] Test History Class
  - [X] ~Test Printer Class~
  - [ ] Test Main Class

**Comment by AZMCode** [comment]
Quick question: Will this feature include the ability to edit answers as one types? Or should I open a separate feature suggestion?

**Comment by keegandonley** [comment]
> Quick question: Will this feature include the ability to edit answers as one types? Or should I open a separate feature suggestion?

@AZMCode could you open a separate feature suggestion and go into a bit more detail of what you're looking for?

**Comment by AZMCode** [comment]
Big Yes. In a moment
