### ISSUE TITLE
Question method without printing newline

### ISSUE THREAD

**Issue by AZMCode** [keegandonley/input-deno#7]
**Is your feature request related to a problem? Please describe.**
I've been trying to make a prompt that looks like a command line, so I tried using the question method.
Turns out I cannot avoid printing that output with a newline, so the prompt looks like this:

```
> 
InputHere
```

Instead of:

`> InputHere`

It might be a good idea to add an optional boolean argument to question, that defaults to true, to allow the user to enable or disable the printing of a final newline in a question.

**Comment by keegandonley** [comment]
@AZMCode this is a good idea, I’ll add this ability!

**Comment by keegandonley** [comment]
@AZMCode This ability has been added in version `1.0.2` (https://github.com/keegandonley/input-deno/releases/tag/1.0.2).

You can now achieve this behavior by doing:

```javascript
const result = 	await input.question("Say something: ", false);
```

**Comment by keegandonley** [comment]
@AZMCode I jumped the gun on the release, the correct version is `1.0.3` (https://github.com/keegandonley/input-deno/releases/tag/1.0.3)

**Comment by AZMCode** [comment]
That was quick. Cheers!
