### ISSUE TITLE
Hidden (Password-Like) Input

### ISSUE THREAD

**Issue by AZMCode** [keegandonley/input-deno#9]
I've been trying to get deno to receive command line input without showing it, kind of like when entering passwords.

It'd be nice to have an option to collect input in this kind of way

While I can technically run the 'stty' linux command to fix this, that solution wouldn't account for cross-platform usage.

TBH, I've been looking around the Deno Runtime API, and I don't think there is native support for this. Maybe a Deno plugin would work? Would that even be within the design goals of this project?

**Comment by keegandonley** [comment]
@AZMCode I can see the value in the ability to hide input like this. This weekend I'll do some investigating into the options for supporting it

**Comment by keegandonley** [comment]
@AZMCode It looks like we can do this behind the `--unstable` flag, so that might be a good approach for the time being until this ability comes into stable release. I can hopefully play with the ability to do this in the next couple days, but feel free to investigate yourself and PR a solution if you manage to get to it before me!

**Comment by AZMCode** [comment]
Thanks!
What was the API you found?

**Comment by keegandonley** [comment]
@AZMCode The method I've been toying with uses `Deno.setRaw()`. I have a draft PR here https://github.com/keegandonley/input-deno/pull/11/files where I got some of the basic functionality working. I'd like this library to not require the `--unstable` flag so I tried to make it still compilable, I don't know if my approach is the best way. Tests aren't passing yet and I haven't updated everywhere to support the new flag but it's a start

**Comment by AZMCode** [comment]
Sounds amazing. Thanks for the effort!

**Comment by keegandonley** [comment]
@AZMCode I haven't forgotten about this, just been so busy lately 😔 . Feel free to take a stab at continuing where my PR left off, but I'm hoping to resume work on it this week

**Comment by AZMCode** [comment]
Sure, np. I'll get on it when I got some free time.
